---
name: Tests
run-name: "Tests (${{ github.head_ref || github.ref_name }})"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check Out Code
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
